[project]
name = "django-notify-hub"
version = "0.1.0"
description = "A reusable Django app for unified notifications (Email, SMS, Push)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=4.2",
    "O365>=2.1",
    "google-api-python-client>=2.187.0",
    "google-auth-oauthlib>=1.2.3",
    "firebase-admin>=7.1.0",
    "phonenumbers>=9.0.21",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
